// cz.config.js
/** @type {import('cz-git').CommitizenGitOptions} */

module.exports = {
	alias: {},
	messages: {
		type: "Que tipo de mudança que você está commitando?",
		scope: "Indique o ESCOPO desta mudança (opcional):",
		customScope: "Indique o ESCOPO desta mudança:",
		subject: "Escreva uma mensagem CURTA e IMPERATIVA que diga oque o seu commit está alterando: ",
		body: "Forneça uma descrição LONGA e DETALHADA sobre o seu commit (opcional). Use \"|\" para quebrar uma nova linha\n",
		breaking: "Liste quaisquer MUDANÇAS DRÁSTICAS (opcional). Use \"|\" para quebrar uma nova linha\n",
		footerPrefixesSelect: "Selecione o tipo de PROBLEMA relacionado a este commit (opcional):",
		customFooterPrefix: "Escreva o prefixo do PROBLEMA:",
		footer: "Liste qualquer PROBLEMA que este commit corrige. Exemplo: #31, #34:\n",
		confirmCommit: "Tem certeza de que deseja continuar com o commit acima?"
	},
	types: [
		{ value: "init",	 		name: "( 🎉 ) Fazendo o commit inicial", emoji: ":tada:" },
		{ value: "feat",	 		name: "( ✨ ) Implementando uma nova funcionalidade.", emoji: ":sparkles:" },
		{ value: "feat", 			name: "( 📱 ) Trabalhando em design responsivo.", emoji: ":iphone:" },
		{ value: "feat",	 		name: "( 💫 ) Adicionando ou atualizando animações e transições.", emoji: ":dizzy:" },
		{ value: "feat",	 		name: "( 🌐 ) Internacionalizando ou localizando.", emoji: ":globe_with_meridians:" },
		{ value: "feat",	 		name: "( 🚸 ) Melhorando a experiência do usuário/usabilidade.", emoji: ":children_crossing:" },
		{ value: "feat",	 		name: "( ♿️) Melhorando a acessibilidade.", emoji: ":wheelchair:" },
		{ value: "feat",	 		name: "( 🥚 ) Adicionando um easter egg.", emoji: ":egg:" },
		{ value: "experiment", 		name: "( ⚗️ ) Experimentando novas coisas.", emoji: ":alembic:" },
		{ value: "wip",				name: "( 🚧 ) Fazendo um trabalho que está em andamento.", emoji: ":construction:" },
		{ value: "breaking change", name: "( 💥 ) Introduzindo mudanças drásticas.", emoji: ":boom:" },
		{ value: "fix",		 		name: "( 🐛 ) Corrigindo um bug.", emoji: ":bug:" },
		{ value: "fix",		 		name: "( ✏️ ) Corrigindo erros de digitação que afetam o funcionamento do código.", emoji: ":pencil:" },
		{ value: "fix",	 			name: "( 🥅 ) Capturando erros.", emoji: ":goal_net:" },
		{ value: "hotfix",		 	name: "( 🚑 ) Corrigindo falha crítica.", emoji: ":ambulance:" },
		{ value: "security",		name: "( 🔒 ) Corrigindo problemas de segurança.", emoji: ":lock:" },
		{ value: "lint",	 		name: "( 🚨 ) Removendo avisos do linter.", emoji: ":rotating_light:" },
		{ value: "types",	 		name: "( 🏷️ ) Adicionando ou atualizando tipos de dados.", emoji: ":label:" },
		{ value: "config",	 		name: "( 🔨 ) Fazendo mudanças que não modificam arquivos de fonte ou de teste.", emoji: ":hammer:" },
		{ value: "performance",	 	name: "( ⚡️) Fazendo mudanças de código que melhoram o desempenho.", emoji: ":zap:" },
		{ value: "deprecate",	 	name: "( 🗑️ ) Depreciando código que precisa ser limpo.", emoji: ":wastebasket:" },
		{ value: "style",	 		name: "( 🎨 ) Melhorando a estrutura / formato do código.", emoji: ":art:" },
		{ value: "style",	 		name: "( 💄 ) Fazendo mudanças que não afetam o significado do código.", emoji: ":lipstick:" },
		{ value: "refactor", 		name: "( ♻️ ) Fazendo mudanças de código que não corrige um bug nem adiciona uma funcionalidade.", emoji: ":recycle:" },
		{ value: "refactor",	 	name: "( 💩 ) Escrevendo código ruim que precisa ser melhorado.", emoji: ":poop:" },
		{ value: "refactor", 	 	name: "( ⚰️ ) Removendo código morto.", emoji: ":coffin:" },
		{ value: "refactor",	 	name: "( 👌 ) Atualizando código devido a mudanças na revisão de código.", emoji: ":ok_hand:" },
		{ value: "refactor",	 	name: "( 🚚 ) Movendo ou renomeando arquivos.", emoji: ":truck:" },
		{ value: "add",	 			name: "( ✨ ) Adicionando códigos ou arquivos.", emoji: ":sparkles:" },
		{ value: "remove",	 		name: "( 🔥 ) Removendo códigos ou arquivos.", emoji: ":fire:" },
		{ value: "chore",	 		name: "( 🚀 ) Fazendo deploy de coisas", emoji: ":rocket:" },
		{ value: "test",	 		name: "( ✅ ) Adicionando testes ausentes ou corrigindo testes existentes.", emoji: ":white_check_mark:" },
		{ value: "dependency",	 	name: "( 👽 ) Atualizando o código devido às mudanças em APIs externas.", emoji: ":alien:" },
		{ value: "dependency",	 	name: "( ⬇️ ) Desatualizando dependências.", emoji: ":arrow_down:" },
		{ value: "dependency",	 	name: "( ⬆️ ) Atualizando dependências.", emoji: ":arrow_up:" },
		{ value: "dependency",	 	name: "( ➕ ) Adicionando dependência.", emoji: ":heavy_plus_sign:" },
		{ value: "dependency",	 	name: "( ➖ ) Removendo dependência.", emoji: ":heavy_minus_sign:" },
		{ value: "build",	 		name: "( 📦️) Fazendo mudanças que afetam o sistema de build ou dependências externas.", emoji: ":package:" },
		{ value: "docs",	 		name: "( 📚 ) Fazendo mudanças apenas na documentação.", emoji: ":books:" },
		{ value: "docs",	 		name: "( 💡 ) Documentando o código fonte.", emoji: ":bulb:" },
		{ value: "docs",		 	name: "( ✏️ ) Corrigindo erros de digitação em comentários ou documentações.", emoji: ":pencil:" },
		{ value: "docs",	 		name: "( 👥 ) Fazendo mudanças nos colaboradores.", emoji: ":busts_in_silhouette:" },
		{ value: "license",	 		name: "( 📄 ) Adicionando ou atualizando licença.", emoji: ":page_facing_up:" },
		{ value: "merge",	 		name: "( 🔀 ) Mesclando branches.", emoji: ":twisted_rightwards_arrows:" },
		{ value: "revert",	 		name: "( ⏪️) Revertendo um commit anterior.", emoji: ":rewind:" },
		{ value: "ignore",	 		name: "( 🙈 ) Adicionando ou atualizando um arquivo \".gitignore.\"", emoji: ":see_no_evil:" }
	],
	useEmoji: true,
	emojiAlign: "left",
	themeColorCode: "",
	scopes: [],
	allowCustomScopes: false,
	allowEmptyScopes: true,
	customScopesAlign: "bottom",
	customScopesAlias: "personalizado",
	emptyScopesAlias: "vazio",
	upperCaseSubject: true,
	markBreakingChangeMode: false,
	allowBreakingChanges: ["feat", "fix"],
	breaklineNumber: 100,
	breaklineChar: "|",
	skipQuestions: [],
	issuePrefixes: [{ value: "closed",name: "fechado:   Os problemas foram processados" }],
	customIssuePrefixAlign: "top",
	emptyIssuePrefixAlias: "vazio",
	customIssuePrefixAlias: "personalizado",
	allowCustomIssuePrefix: true,
	allowEmptyIssuePrefix: true,
	confirmColorize: true,
	maxHeaderLength: 80,
	maxSubjectLength: Infinity,
	minSubjectLength: 10,
	scopeOverrides: undefined,
	defaultBody: "",
	defaultIssues: "",
	defaultScope: "",
	defaultSubject: ""
};